### ISSUE TITLE
YAML 标记语言

### ISSUE THREAD

**Issue by huliuqing** [huliuqing/phpnotes#60]
### 什么是 YAML ?

[YAML Wiki](https://zh.wikipedia.org/wiki/YAML) :它是 Yet Another Markup Language 简写，即又一个标记语言，它是一门语法简洁，功能强大的语言。
本质上它是一种通用的数据串行化格式，通常用它来编写配置文件。

### 语法规则
以 [JS-YAML](https://github.com/nodeca/js-yaml) 为例的[在线 Demo](http://nodeca.github.io/js-yaml/)
1. 大小写敏感
2. 使用缩进表示层级关系
3. 缩进仅能使用空格
4. 缩进时空格数目不重要，只要相同层级的元素左侧对齐即可
5. <code>#</code> 表示注释
6. 支持的数据结构
6.1 对象：键值对的集合
6.2 数组
6.3 标量
6.3.1 string
6.3.2 boolean
6.3.3 integer
6.3.4 float
6.3.5 null
6.3.6 time
6.3.7 date
7. 使用 <code>!!</code> 强制类型转换

#### 对象

语法： 对象为一组键值对，使用冒号结构表示

1. YAML 基础对象表示如下：

```yaml
animal: pets
```

转换为 JavaScript 格式如下:

```javascript
{ animal: 'pets' }
```

2. 值为对象的对象表示:
```yaml
user: { name: Jobs, age: 18 }
```

转换为 JavaScript 格式如下:

```javascript
{ user: { name: 'Jobs', age: 18} }
```

#### 数组

语法: 以连词线 <code>-</code> ,开头的行

1. 数组值为标量值表示法

```yaml
- yaml
- javascript
- php
```

转换为 JavaScript 格式如下:

```javascript
[ 'yaml', 'javascript', 'php' ]
```

2. 值为数组的表示法：

```yaml
languages :
-
 - PHP
 - Perl
 - Python
```

转换为 JavaScript 格式如下:

```javascript
{ languages: [ [ 'PHP', 'Perl', 'Python' ] ] }
```

3. 数组的行内表示：

```yaml
tools: [VS Code, Sublime, Notepad++]
```

转换为 JavaScript 格式如下:

```javascript
{  tools: [ 'VS Code', 'Sublime', 'Notepad++' ] }
```

#### 标量
1. integer 和 float
```yaml
age: 10
pi: 3.14
```

```javascript
{
    age: 10, 
    pi: 3.14
}
```

2. boolean

```yaml
hasUser: true
```

```javascript
{ hasUser: true}
```

3 null

```yaml
parent: ~
anotherParent: null
```

```javascript
{ parent: null, anotherParent: null }
```

4 时间
```yaml
timestamp:
  canonical:        2001-12-15T02:59:43.1Z
  valid iso8601:    2001-12-14t21:59:43.10-05:00
  space separated:  2001-12-14 21:59:43.10 -5
  no time zone (Z): 2001-12-15 2:59:43.10
  date (00:00:00Z): 2002-12-14
```

```javascript
{timestamp: 
    { 
        canonical: Sat Dec 15 2001 10:59:43 GMT+0800 (中国标准时间),
        'valid iso8601': Sat Dec 15 2001 10:59:43 GMT+0800 (中国标准时间),
        'space separated': Sat Dec 15 2001 10:59:43 GMT+0800 (中国标准时间),
        'no time zone (Z)': Sat Dec 15 2001 10:59:43 GMT+0800 (中国标准时间),
        'date (00:00:00Z)': Sat Dec 14 2002 08:00:00 GMT+0800 (中国标准时间) 
    }
}
```

#### 强制类型转换

```yaml
toString: !!str 123

# result
{ toString: '123' }

toUndefined: !!js/undefined ~

# result
{ toUndefined: undefined }
```

### 学习资源
[YAML](http://yaml.org/)
[YAML 语言教程](http://www.ruanyifeng.com/blog/2016/07/yaml.html?f=tt)
[YAML tool](http://nodeca.github.io/js-yaml/)
